// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0kBES-lJ6qljfKI0Xs2fYaLpia-lsFuA',
    appId: '1:577302724223:android:7925f026c2cee3543d894a',
    messagingSenderId: '577302724223',
    projectId: 'sandesh-718d6',
    storageBucket: 'sandesh-718d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHDNf4sB58UB63NDLhWFOuHaQGohD60T4',
    appId: '1:577302724223:ios:8b9198c84707b5fc3d894a',
    messagingSenderId: '577302724223',
    projectId: 'sandesh-718d6',
    storageBucket: 'sandesh-718d6.appspot.com',
    androidClientId: '577302724223-gpntto2pomv95o0lgrodchbqhgs65585.apps.googleusercontent.com',
    iosClientId: '577302724223-chtikv31tvjv4kr9edgt3o01vt51vofk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
